<li>able</li>
<li>clean</li>
<li>enthusiastic</li>
<li>heartening</li>
<li>meek</li>
<li>reasonable</li>
<li>talented
accommodating</li>
<li>clever</li>
<li>ethical</li>
<li>helpful</li>
<li>meritorious</li>
<li>refined</li>
<li>temperate
accomplished</li>
<li>commendable</li>
<li>excellent</li>
<li>high-class</li>
<li>moral</li>
<li>reliable</li>
<li>terrific
adept</li>
<li>compassionate</li>
<li>exceptional</li>
<li>honest</li>
<li>neat</li>
<li>remarkable</li>
<li>tidy
admirable</li>
<li>composed</li>
<li>exemplary</li>
<li>honorable</li>
<li>noble</li>
<li>resilient</li>
<li>top</li>
<li>quality
agreeable</li>
<li>considerate</li>
<li>exquisite</li>
<li>hopeful</li>
<li>obliging</li>
<li>respectable</li>
<li>tremendous
amazing</li>
<li>consummate</li>
<li>extraordinary</li>
<li>humble</li>
<li>observant</li>
<li>respectful</li>
<li>trustworthy
appealing</li>
<li>cooperative</li>
<li>fabulous</li>
<li>important</li>
<li>optimistic</li>
<li>resplendent</li>
<li>trusty
astute</li>
<li>correct</li>
<li>faithful</li>
<li>impressive</li>
<li>organized</li>
<li>responsible</li>
<li>truthful
attractive</li>
<li>courageous</li>
<li>fantastic</li>
<li>incisive</li>
<li>outstanding</li>
<li>robust</li>
<li>unbeatable
awesome</li>
<li>courteous</li>
<li>fascinating</li>
<li>incredible</li>
<li>peaceful</li>
<li>selfless</li>
<li>understanding
beautiful</li>
<li>dazzling</li>
<li>fine</li>
<li>innocent</li>
<li>perceptive</li>
<li>sensational</li>
<li>unequaled
benevolent</li>
<li>decent</li>
<li>first-class</li>
<li>insightful</li>
<li>perfect</li>
<li>sensible</li>
<li>unparalleled
brave</li>
<li>delightful</li>
<li>fortitudinous</li>
<li>inspiring</li>
<li>pleasant</li>
<li>serene</li>
<li>upbeat
breathtaking</li>
<li>dependable</li>
<li>gallant</li>
<li>intelligent</li>
<li>pleasing</li>
<li>sharp</li>
<li>valiant
bright</li>
<li>devoted</li>
<li>generous</li>
<li>joyful</li>
<li>polite</li>
<li>shining</li>
<li>valuable
brilliant</li>
<li>diplomatic</li>
<li>gentle</li>
<li>judicious</li>
<li>positive</li>
<li>shrewd</li>
<li>vigilant
bubbly</li>
<li>discerning</li>
<li>gifted</li>
<li>just</li>
<li>praiseworthy</li>
<li>smart</li>
<li>vigorous
buoyant</li>
<li>disciplined</li>
<li>giving</li>
<li>kindly</li>
<li>precious</li>
<li>sparkling</li>
<li>virtuous
calm</li>
<li>elegant</li>
<li>gleaming</li>
<li>laudable</li>
<li>priceless</li>
<li>spectacular</li>
<li>well</li>
<li>mannered
capable</li>
<li>elevating</li>
<li>glowing</li>
<li>likable</li>
<li>principled</li>
<li>splendid</li>
<li>wholesome
charitable</li>
<li>enchanting</li>
<li>good</li>
<li>lovable</li>
<li>prompt</li>
<li>steadfast</li>
<li>wise
charming</li>
<li>encouraging</li>
<li>gorgeous</li>
<li>lovely</li>
<li>prudent</li>
<li>stunning</li>
<li>witty
chaste</li>
<li>endearing</li>
<li>graceful</li>
<li>loyal</li>
<li>punctual</li>
<li>super</li>
<li>wonderful
cheerful</li>
<li>energetic</li>
<li>gracious</li>
<li>luminous</li>
<li>pure</li>
<li>superb</li>
<li>worthy
chivalrous</li>
<li>engaging</li>
<li>great</li>
<li>magnanimous</li>
<li>quick</li>
<li>superior</li>
<li>zesty
gallant</li>
<li>enhanced</li>
<li>happy</li>
<li>magnificent</li>
<li>radiant</li>
<li>supportive</li>
<li>civil</li>
<li>enjoyable</li>
<li>hardy</li>
<li>marvelous</li>
<li>rational</li>
<li>supreme</li>